# Generated by Django 3.1.2 on 2020-10-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
